### ISSUE TITLE
Doesn't Work with pfSense 2.4.4

### ISSUE THREAD

**Issue by RichieRogers** [KoenZomers/pfSenseBackup#5]
Hi,
/unfortunately, since upgrading to pfSense 2.4.4 I can no longer use this to create daily backus.
I get the following error:

pfSense Backup Tool v2.4.3 by Koen Zomers

Connecting using protocol version 2.3
Authenticating
Requesting backup file
Retrieving backup file
No valid backup contents returned

Any chance of this being fixed?
Richie

**Comment by jvivona** [comment]
OK - I just realized I am still using pfsensebackup 2.4.2 and it works against pfsense 2.4.4 on a range of both local and remote devices.

I will check with 2.4.3 and report back.

@RichieRogers do you still have 2.4.2  around and able to test it?

**Comment by KoenZomers** [comment]
@RichieRogers It should work just fine against 2.4.4. Tested it here on several boxes and it works flawlessly. Typically when I get reports like this people are either still using the -v argument which you shouldn't anymore with the current latest version or people are using SSL and are forgetting to include the -usessl flag. Can you verify both?

Otherwise a really easy way to discover where things are going wrong is to use Fiddler while running the backup command. It will show you all the network traffic it generates including exact details where and why it fails to download the backup.

**Comment by RichieRogers** [comment]
Hi,
I was still using the "v" switch.
As soon as I removed that it worked fine.
I hadn't realised you weren't supposed to use it any more.
Thanks for your help,
Richie
